### ISSUE TITLE
Problem in WavCraft servise

### ISSUE THREAD

**Issue by netagl** [JinhuaLiang/WavCraft#4]
Hi, Im trying to inference WavCraft, but getting an error
I exported openAi and HF keys, and followd the ReadMe instruction:

First:
`source scripts/setup_envs.sh
`

Then:
`export OPENAI_KEY=YOUR_OPENAI_KEY
export HF_KEY=YOUR_HF_KEY`

and finally:
`python3 WavCraft.py basic -f \
--input-wav assets/duck_quacking_in_water.wav \
--input-text "Add dog barking."`

but getting:
```
python3 WavCraft.py basic -f \
> --input-wav assets/duck_quacking_in_water.wav \
> --input-text "Add dog barking."
New session created, session_id=20240909180933_33o75bjk
Session 20240909180933_33o75bjk is created.
session_id=20240909180933_33o75bjk, Step 1: Writing executable code with LLM ...
    trying ...
session_id=20240909180933_33o75bjk, Step 2: Start running Python program...
Traceback (most recent call last):
  File "/opt/conda/envs/wavcraft/lib/python3.9/site-packages/urllib3/util/url.py", line 425, in parse_url
    host, port = _HOST_PORT_RE.match(host_port).groups()  # type: ignore[union-attr]
AttributeError: 'NoneType' object has no attribute 'groups'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/wavcraft/lib/python3.9/site-packages/requests/models.py", line 433, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/opt/conda/envs/wavcraft/lib/python3.9/site-packages/urllib3/util/url.py", line 451, in parse_url
    raise LocationParseError(source_url) from e
urllib3.exceptions.LocationParseError: Failed to parse: http://None:None/generate_audio

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/Projects/TTS/WavCraft/output/sessions/20240909180933_33o75bjk/audio_executable.py", line 6, in <module>
    WAV1 = TTA(text="dog barking", length=LEN(INPUT_WAV0), volume=5)
  File "/opt/conda/envs/wavcraft/lib/python3.9/site-packages/retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/opt/conda/envs/wavcraft/lib/python3.9/site-packages/retrying.py", line 266, in call
    raise attempt.get()
  File "/opt/conda/envs/wavcraft/lib/python3.9/site-packages/retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/conda/envs/wavcraft/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/opt/conda/envs/wavcraft/lib/python3.9/site-packages/retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/ec2-user/Projects/TTS/WavCraft/wavcraft/apis.py", line 405, in TTA
    response = requests.post(url, json=data)
  File "/opt/conda/envs/wavcraft/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/opt/conda/envs/wavcraft/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/conda/envs/wavcraft/lib/python3.9/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/opt/conda/envs/wavcraft/lib/python3.9/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/opt/conda/envs/wavcraft/lib/python3.9/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "/opt/conda/envs/wavcraft/lib/python3.9/site-packages/requests/models.py", line 435, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: http://None:None/generate_audio
Audio editor took 15.18 seconds to complete.

```

would love to get some help
thank you!

**Comment by JinhuaLiang** [comment]
Hi, many thanks for your interest in our work. Before playing with WavCraft, you should launch expert models on your local using
`source scripts/start_services.sh`

You will check the relevant log for successful app launch.
